 # Deploy a Producción (automatizado)
name: Deploy to Production (Render) from Main

on:
  push:
    branches:
      - main

jobs:
  deploy-production:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/miapp-node-express:latest .

      - name: Push image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/miapp-node-express:latest

      - name: Deploy to Render PRODUCCIÓN
        run: curl -X POST ${{ secrets.RENDER_PROD_HOOK }}
