name: CI/CD for Main (Production)

on:
  # Se activa cuando se hace push a la rama main
  push:
    branches:
      - main
  # Se activa también cuando se abre un Pull Request hacia main
  pull_request:
    branches:
      - main

jobs:
  test: # Este job se ejecutará siempre (en push y en pull_request)
    name: Run Unit & Integration Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test
        env:
          # Pasamos todas las variables necesarias para construir la URI en el entorno de testing
          MONGO_USER: ${{ secrets.MONGO_USER }}
          MONGO_PWD: ${{ secrets.MONGO_PWD }}
          MONGO_DB: ${{ secrets.MONGO_DB }}
          MONGO_HOST: ${{ secrets.MONGO_HOST }}
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
          PORT: 3000


  # --- Jobs de Despliegue a Producción ---
  # Estos jobs SÓLO deben ejecutarse en un PUSH, no en un PULL REQUEST.
  build-and-push-docker:
    name: Build and Push Docker Image
    # Condición: Ejecutar este job SÓLO si el evento fue un 'push'
    if: github.event_name == 'push'
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          # Usamos 'latest' para la imagen de producción
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/gestion-de-reservas:latest

  deploy:
    name: Deploy to Render
    # Condición: Ejecutar este job SÓLO si el evento fue un 'push'
    needs: build-and-push-docker
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render Deploy
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            -d '{}' \
            https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID_MAIN }}/deploys
